### ISSUE TITLE
пук

### ISSUE THREAD

**Issue by KocTu4eK** [VinkyV/BedrockHub#1]
дабавьте пожалуйста в документацию гайд на как написать античит от киллауры

**Comment by KoshakMineDEV** [comment]
Добавлю в документацию по наккиту как запретить костику заходить на сервер😊

**Comment by VinkyV** [comment]
> дабавьте пожалуйста в документацию гайд на как написать античит от киллауры
На Nukkit или на LiteLoaderBDS?

**Comment by KoshakMineDEV** [comment]
Костик молчит, закрываем контору

**Comment by KocTu4eK** [comment]
кошак иди нахуй

**Comment by KocTu4eK** [comment]
> 

это рофл. а вообще, если серьёзно, то можно как пример плагина что-то подобное в лл доку запихать.

**Comment by KocTu4eK** [comment]
> > дабавьте пожалуйста в документацию гайд на как написать античит от киллауры
> 
> На Nukkit или на LiteLoaderBDS?

это рофл. а вообще, если серьёзно, то можно как пример плагина что-то подобное в лл доку запихать.

**Comment by KocTu4eK** [comment]
> Могу, это тупо фэйк игрок за спиной подозреваемого, если он по нему ударит, то пизда игроку.

ну го

**Comment by VinkyV** [comment]
> ну го
Ок мб бахну на BedrockHub)
